 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/candidatures", type: :request do
  
  # Candidature. As you add validations to Candidature, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Candidature.create! valid_attributes
      get candidatures_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      candidature = Candidature.create! valid_attributes
      get candidature_url(candidature)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_candidature_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      candidature = Candidature.create! valid_attributes
      get edit_candidature_url(candidature)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Candidature" do
        expect {
          post candidatures_url, params: { candidature: valid_attributes }
        }.to change(Candidature, :count).by(1)
      end

      it "redirects to the created candidature" do
        post candidatures_url, params: { candidature: valid_attributes }
        expect(response).to redirect_to(candidature_url(Candidature.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Candidature" do
        expect {
          post candidatures_url, params: { candidature: invalid_attributes }
        }.to change(Candidature, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post candidatures_url, params: { candidature: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested candidature" do
        candidature = Candidature.create! valid_attributes
        patch candidature_url(candidature), params: { candidature: new_attributes }
        candidature.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the candidature" do
        candidature = Candidature.create! valid_attributes
        patch candidature_url(candidature), params: { candidature: new_attributes }
        candidature.reload
        expect(response).to redirect_to(candidature_url(candidature))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        candidature = Candidature.create! valid_attributes
        patch candidature_url(candidature), params: { candidature: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested candidature" do
      candidature = Candidature.create! valid_attributes
      expect {
        delete candidature_url(candidature)
      }.to change(Candidature, :count).by(-1)
    end

    it "redirects to the candidatures list" do
      candidature = Candidature.create! valid_attributes
      delete candidature_url(candidature)
      expect(response).to redirect_to(candidatures_url)
    end
  end
end
