 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/manager/profiles", type: :request do
  
  # Manager::Profile. As you add validations to Manager::Profile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Manager::Profile.create! valid_attributes
      get manager_profiles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      profile = Manager::Profile.create! valid_attributes
      get manager_profile_url(manager_profile)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_manager_profile_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      profile = Manager::Profile.create! valid_attributes
      get edit_manager_profile_url(manager_profile)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Manager::Profile" do
        expect {
          post manager_profiles_url, params: { manager_profile: valid_attributes }
        }.to change(Manager::Profile, :count).by(1)
      end

      it "redirects to the created manager_profile" do
        post manager_profiles_url, params: { manager_profile: valid_attributes }
        expect(response).to redirect_to(manager_profile_url(@manager_profile))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Manager::Profile" do
        expect {
          post manager_profiles_url, params: { manager_profile: invalid_attributes }
        }.to change(Manager::Profile, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post manager_profiles_url, params: { manager_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manager_profile" do
        profile = Manager::Profile.create! valid_attributes
        patch manager_profile_url(manager_profile), params: { manager_profile: new_attributes }
        profile.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the manager_profile" do
        profile = Manager::Profile.create! valid_attributes
        patch manager_profile_url(manager_profile), params: { manager_profile: new_attributes }
        profile.reload
        expect(response).to redirect_to(manager_profile_url(profile))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        profile = Manager::Profile.create! valid_attributes
        patch manager_profile_url(manager_profile), params: { manager_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested manager_profile" do
      profile = Manager::Profile.create! valid_attributes
      expect {
        delete manager_profile_url(manager_profile)
      }.to change(Manager::Profile, :count).by(-1)
    end

    it "redirects to the manager_profiles list" do
      profile = Manager::Profile.create! valid_attributes
      delete manager_profile_url(manager_profile)
      expect(response).to redirect_to(manager_profiles_url)
    end
  end
end
