name: "Ruby on Rails CI"
on: push
#  pull_request:
#    branches:
#      - main
#      - 'release/*'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: startup_mission_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/startup_mission_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag startup_mission
      - name: Set up database schema
        run: docker run --network host -e DATABASE_URL=postgres://rails:password@localhost:5432/startup_mission_test startup_mission bin/rails db:migrate
      - name: Run Tests
        run: docker run --network host -e DATABASE_URL=postgres://rails:password@localhost:5432/startup_mission_test startup_mission bundle exec rspec --exclude-pattern 'spec/features/**/*_spec.rb' --format progress
        env:
          GITHUB_KEY: ${{ secrets.API_GITHUB_KEY }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Run RubyCritic score check
        run: bundle exec rake rubycritic:check_score
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
